%ifidn __OUTPUT_FORMAT__, win64
%define WINABI
%define r0 rcx
%define r1 rdx
%define r2 r8
%define r3 r9
%define r4 rsi
%define r5 rdi
%define r6 rbp
%define r7 rbx
%else
%define r0 rdi
%define r1 rsi
%define r2 rdx
%define r3 rcx
%define r4 r8
%define r5 r9
%define r6 rbp
%define r7 rbx
%endif
%if vsize == 32
%define a xmm0
%define b xmm1
%define c xmm2
%define d xmm3
%define e xmm4
%define f xmm5
%define g xmm6
%define h xmm7
%define i xmm8
%define k xmm9
%define n xmm10
%define p xmm11
%define r xmm12
%define t xmm13
%define u xmm14
%define v xmm15
%define A ymm0
%define B ymm1
%define C ymm2
%define D ymm3
%define E ymm4
%define F ymm5
%define G ymm6
%define H ymm7
%define I ymm8
%define K ymm9
%define N ymm10
%define P ymm11
%define R ymm12
%define T ymm13
%define U ymm14
%define V ymm15 
%endif
%if vsize == 64
%define a ymm0
%define b ymm1
%define c ymm2
%define d ymm3
%define e ymm4
%define f ymm5
%define g ymm6
%define h ymm7
%define i ymm8
%define k ymm9
%define n ymm10
%define p ymm11
%define r ymm12
%define t ymm13
%define u ymm14
%define v ymm15
%define A zmm0
%define B zmm1
%define C zmm2
%define D zmm3
%define E zmm4
%define F zmm5
%define G zmm6
%define H zmm7
%define I zmm8
%define K zmm9
%define N zmm10
%define P zmm11
%define R zmm12
%define T zmm13
%define U zmm14
%define V zmm15
%endif
