%define a xmm0
%define b xmm1
%define c xmm2
%define d xmm3
%define e xmm4
%define f xmm5
%define g xmm6
%define h xmm7
%define i xmm8
%define k xmm9
%define n xmm10
%define p xmm11
%define r xmm12
%define t xmm13
%define u xmm14
%define v xmm15
%define A ymm0
%define B ymm1
%define C ymm2
%define D ymm3
%define E ymm4
%define F ymm5
%define G ymm6
%define H ymm7
%define I ymm8
%define K ymm9
%define N ymm10
%define P ymm11
%define R ymm12
%define T ymm13
%define U ymm14
%define V ymm15
